include:
    -   project: 'indus/ci/templates'
        file: all.yml
        ref: v1
    -   local: '.cd/gitlab-cd.yml'
    #-   local: '/.ci/checker/gitlab-ci-checker.yml' # https://gitlab.eolas.fr/indus/ci/ci-checker

variables:
    CI_PHP_IMAGE: '$CI_REGISTRY/indus/docker/images/phpfpm:8.2'
    COMPOSER_VERSION: 2
    NODE_VERSION: 14

stages:
    - checker
    - test
    - deploy

before_script:
    # Déclaration des variables d'environnement liées à Docker pour ne pas gêner le parsing du .env par défaut
    - 'cat .docker/.env .env > .env.local'

SonarQube:
    extends: .indus-sonarqube


Dépendances valides:
    image:
        name: '$CI_PHP_IMAGE'
        entrypoint: [ "" ]
    rules:
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
            changes: [ 'composer.json', 'composer.lock' ]
    script:
        - 'composer validate --strict'
